  [31m×[0m I didn't find any validator matching your criteria.
[36m  help: [0mHere's a list of all validators I've found in your project. Please
        double-check this list against the options that you've provided:
        
        → alwayssucceedsalwaysfails.alwaysFails
        → alwayssucceedsalwaysfails.alwaysSucceeds
        → commonconditions.conditionator
        → toosimple_validators.datum22
        → toosimple_validators.datumVSredeemer
        → toosimple_validators.redeemer11
        → typed_validators.datumVSredeemer
        → typed_validators.ourWonderfullValidator
        → typed_validators.typedRedeemer11
        → typed_validators.typeddatum22

